### ISSUE TITLE
Bitbucket LFS

### ISSUE THREAD

**Issue by pdf** [bozaro/git-lfs-java#3]
EDIT: Apologies, I was browsing the source trying to determine how the URIs are constructed, I believe this belongs [here](https://github.com/bozaro/git-lfs-migrate/issues/13)

**Comment by bozaro** [comment]
Unfortunately I am offline now. I will see this issue in two weeks.10:27, 19 июля 2016 г., Peter Fern <notifications@github.com>:Closed #3. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.     Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
